### ISSUE TITLE
Fresh default deployment on Railway crashes

### ISSUE THREAD

**Issue by betterprompts** [Grey-A/heavyweight-fastapi#1]
```
File "/root/.nix-profile/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete

return future.result()

File "/opt/venv/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve

config.load()

File "/opt/venv/lib/python3.8/site-packages/uvicorn/config.py", line 467, in load

self.loaded_app = import_from_string(self.app)

File "/opt/venv/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string

module = importlib.import_module(module_str)

File "/root/.nix-profile/lib/python3.8/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

File "<frozen importlib._bootstrap>", line 991, in _find_and_load

File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 843, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/app/app/main.py", line 3, in <module>

from app.user.apis import router as user_router

File "/app/app/user/apis.py", line 5, in <module>

from app.user import schemas, services

File "/app/app/user/schemas.py", line 17, in <module>

class User(BaseUser):

File "/app/app/user/schemas.py", line 19, in User

last_login: datetime | None = Field(description="The User's last login date")

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.

INFO  [alembic.runtime.migration] Will assume transactional DDL.

Traceback (most recent call last):

File "/opt/venv/bin/uvicorn", line 8, in <module>

sys.exit(main())

File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__

return self.main(*args, **kwargs)

File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1078, in main

rv = self.invoke(ctx)

File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke

return ctx.invoke(self.callback, **ctx.params)

File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke

return __callback(*args, **kwargs)

File "/opt/venv/lib/python3.8/site-packages/uvicorn/main.py", line 416, in main

run(

File "/opt/venv/lib/python3.8/site-packages/uvicorn/main.py", line 587, in run

server.run()

File "/opt/venv/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run

return asyncio.run(self.serve(sockets=sockets))

File "/root/.nix-profile/lib/python3.8/asyncio/runners.py", line 44, in run

return loop.run_until_complete(main)

File "/root/.nix-profile/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete

return future.result()

File "/opt/venv/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve

config.load()

File "/opt/venv/lib/python3.8/site-packages/uvicorn/config.py", line 467, in load

self.loaded_app = import_from_string(self.app)

File "/opt/venv/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string

module = importlib.import_module(module_str)

File "/root/.nix-profile/lib/python3.8/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

File "<frozen importlib._bootstrap>", line 991, in _find_and_load

File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 843, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/app/app/main.py", line 3, in <module>

from app.user.apis import router as user_router

File "/app/app/user/apis.py", line 5, in <module>

from app.user import schemas, services

File "/app/app/user/schemas.py", line 17, in <module>

class User(BaseUser):

File "/app/app/user/schemas.py", line 19, in User

last_login: datetime | None = Field(description="The User's last login date")

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by Grey-A** [comment]
@betterprompts  The issue here is from the NIXPACKS builder, it uses an older version of python which doesn't support `|`  and other type hints like `list(students)` for example.

The solution is to specify a `NIXPACKS_PYTHON_VERSION` in your railway variables and set it to the latest version `3.11`

I thought i added it before i deployed the template, thank you for drawing my attention to this

**Comment by Grey-A** [comment]
I made the change to the template, in your railway variables add

NIXPACKS_PYTHON_VERSION and set it to 3.11

that should fix the issue

**Comment by Grey-A** [comment]
If you have any more questions please feel free to ask

**Comment by betterprompts** [comment]
Thank you!
